# Generated by Django 3.0 on 2021-11-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_auto_20211116_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
