# Generated by Django 3.0 on 2021-11-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_problem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='Problem 1', max_length=255),
            preserve_default=False,
        ),
    ]
