# Generated by Django 3.0 on 2021-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_problem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='type',
        ),
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
