# Generated by Django 3.0 on 2021-11-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_auto_20211119_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='test',
        ),
    ]
