# Generated by Django 3.0 on 2021-11-21 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0006_remove_submission_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 9, 6, 43, 346072, tzinfo=utc)),
        ),
    ]
