# Generated by Django 3.0 on 2021-11-21 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_remove_test_has_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 18, 29, 8, 68808, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
