# Generated by Django 3.0 on 2021-11-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0010_test_end_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSubmission',
        ),
    ]
