# Generated by Django 3.0 on 2021-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0011_delete_testsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.TextField(default='coding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.TextField(default='submitted'),
        ),
    ]
