# Generated by Django 3.0 on 2021-11-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0013_auto_20211124_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.TextField(default='unidentified'),
        ),
    ]
