# Generated by Django 3.0 on 2021-11-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0014_submission_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='after_completion',
        ),
    ]
